# Generated by Django 6.0.3 on 2026-03-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
